name: xarray
channels:
  - conda-forge
  - intake
  - default
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - dask
  - distributed
  - bokeh
  - holoviews
  - geoviews
  - netcdf4
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - graphviz
